<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ChevronLeft, Loader2 } from 'lucide-vue-next'
import { createBuyerAfterSale, initiateBuyerAfterSaleDispute, type CreateAfterSaleResult } from '@/api/afterSales'
import { cancelBuyerOrder, confirmBuyerOrderReceipt, createEmptyBuyerOrderDetail, getBuyerOrderDetail, getBuyerOrderStatusMeta, type BuyerOrderDetail } from '@/api/orders'
import OrderMessagePanel from '@/pages/orders/components/OrderMessagePanel.vue'
import CommerceOrderProductSnapshot from '@/components/commerce/CommerceOrderProductSnapshot.vue'
import CommerceOrderStatusSteps from '@/components/commerce/CommerceOrderStatusSteps.vue'

const route = useRoute(); const loading = ref(false); const hasLoadedOnce = ref(false); const errorMessage = ref(''); const detail = ref<BuyerOrderDetail>(createEmptyBuyerOrderDetail())
const actionSubmitting = ref(false); const actionErrorMessage = ref(''); const actionSuccessMessage = ref(''); const cancelReason = ref('')
const afterSaleSubmitting = ref(false); const afterSaleErrorMessage = ref(''); const afterSaleSuccessMessage = ref(''); const createdAfterSaleId = ref<number | null>(null); const afterSaleForm = reactive({ reason: '', evidenceImageText: '' })
const disputeSubmitting = ref(false); const disputeErrorMessage = ref(''); const disputeSuccessMessage = ref(''); const disputeForm = reactive({ afterSaleId: '', content: '' })
const orderId = computed(() => { const raw = route.params.orderId; return Array.isArray(raw) ? raw[0] || '' : typeof raw === 'string' ? raw : '' })
const statusMeta = computed(() => getBuyerOrderStatusMeta(detail.value.status)); const primaryProductImage = computed(() => detail.value.productImages[0] || detail.value.productThumbnail)
const canEnterPaymentPage = computed(() => detail.value.orderId !== null && detail.value.status === 'pending' && !loading.value && !actionSubmitting.value && !afterSaleSubmitting.value && !disputeSubmitting.value)
const canTriggerCancel = computed(() => canEnterPaymentPage.value)
const canTriggerConfirmReceipt = computed(() => detail.value.orderId !== null && detail.value.status === 'shipped' && !loading.value && !actionSubmitting.value && !afterSaleSubmitting.value && !disputeSubmitting.value)
function readPositiveInt(value: unknown) { if (typeof value === 'number' && Number.isInteger(value) && value > 0) return value; if (typeof value === 'string' && /^\d+$/.test(value.trim())) { const parsed = Number(value.trim()); return parsed > 0 ? parsed : null } return null }
function parseDateTime(value: string) { const normalized = value.trim(); if (!normalized) return null; const iso = new Date(normalized.replace(' ', 'T')); if (!Number.isNaN(iso.getTime())) return iso; const fallback = new Date(normalized.replace(/-/g, '/')); return Number.isNaN(fallback.getTime()) ? null : fallback }
function readHoursSinceCompleteTime(value: string) { const parsed = parseDateTime(value); return parsed ? (Date.now() - parsed.getTime()) / 3600000 : null }
function normalizeEvidenceImagesFromText(value: string) { const normalized = value.trim(); return normalized ? Array.from(new Set(normalized.split(/[\n,;]/g).map((item) => item.trim()).filter(Boolean))) : [] }
const canTriggerAfterSaleApply = computed(() => { if (detail.value.orderId === null || detail.value.status !== 'completed' || loading.value || actionSubmitting.value || afterSaleSubmitting.value || disputeSubmitting.value) return false; const hours = readHoursSinceCompleteTime(detail.value.completeTime); if (hours === null || hours < 0 || hours > 24 * 7) return false; const reason = afterSaleForm.reason.trim(); return reason.length >= 2 && reason.length <= 200 && normalizeEvidenceImagesFromText(afterSaleForm.evidenceImageText).length <= 3 })
const canTriggerDisputeInitiate = computed(() => !loading.value && !actionSubmitting.value && !afterSaleSubmitting.value && !disputeSubmitting.value && readPositiveInt(disputeForm.afterSaleId) !== null && disputeForm.content.trim().length >= 2 && disputeForm.content.trim().length <= 500)
const afterSaleHint = computed(() => { if (detail.value.status !== 'completed') return ''; const hours = readHoursSinceCompleteTime(detail.value.completeTime); if (hours === null || hours < 0) return '暂无法确认售后时限，请以提交结果为准。'; return hours > 24 * 7 ? '已超过订单完成后的 7 天售后申请时间。' : '订单完成后 7 天内可申请售后。' })
function readErrorMessage(error: unknown, fallback = '请求失败，请稍后重试。') { return error instanceof Error && error.message.trim() ? error.message : fallback }
function clearActionMessages() { if (!actionSubmitting.value) { actionErrorMessage.value = ''; actionSuccessMessage.value = '' } }
function clearAfterSaleMessages() { if (!afterSaleSubmitting.value) { afterSaleErrorMessage.value = ''; afterSaleSuccessMessage.value = '' } }
function clearDisputeMessages() { if (!disputeSubmitting.value) { disputeErrorMessage.value = ''; disputeSuccessMessage.value = '' } }
function readAfterSaleSuccessMessage(result: CreateAfterSaleResult) { return result.afterSaleId !== null ? `售后申请已提交，售后单号：${result.afterSaleId}` : '售后申请已提交。' }
async function submitCancelOrder() { if (!canTriggerCancel.value || detail.value.orderId === null) return; const reason = cancelReason.value.trim(); if (reason.length > 100) { actionErrorMessage.value = '取消原因不能超过 100 个字。'; actionSuccessMessage.value = ''; return } actionErrorMessage.value = ''; actionSuccessMessage.value = ''; try { actionSubmitting.value = true; actionSuccessMessage.value = await cancelBuyerOrder(detail.value.orderId, { reason: reason || undefined }) || '取消订单请求已提交。'; await loadDetail() } catch (error: unknown) { actionSuccessMessage.value = ''; actionErrorMessage.value = readErrorMessage(error, '订单操作失败，请稍后重试。') } finally { actionSubmitting.value = false } }
async function submitConfirmReceipt() { if (!canTriggerConfirmReceipt.value || detail.value.orderId === null) return; actionErrorMessage.value = ''; actionSuccessMessage.value = ''; try { actionSubmitting.value = true; actionSuccessMessage.value = await confirmBuyerOrderReceipt(detail.value.orderId) || '确认收货请求已提交。'; await loadDetail() } catch (error: unknown) { actionSuccessMessage.value = ''; actionErrorMessage.value = readErrorMessage(error, '订单操作失败，请稍后重试。') } finally { actionSubmitting.value = false } }
async function submitAfterSaleApply() { if (afterSaleSubmitting.value || detail.value.orderId === null) return; if (detail.value.status !== 'completed') { afterSaleErrorMessage.value = '仅已完成订单可申请售后。'; return } const hours = readHoursSinceCompleteTime(detail.value.completeTime); const reason = afterSaleForm.reason.trim(); const evidenceImages = normalizeEvidenceImagesFromText(afterSaleForm.evidenceImageText); if (hours === null || hours < 0 || hours > 24 * 7) { afterSaleErrorMessage.value = '当前订单不在可申请售后的时间范围内。'; return } if (reason.length < 2 || reason.length > 200) { afterSaleErrorMessage.value = '售后原因需为 2 至 200 个字。'; return } if (evidenceImages.length > 3) { afterSaleErrorMessage.value = '凭证图片链接最多填写 3 个。'; return } afterSaleErrorMessage.value = ''; afterSaleSuccessMessage.value = ''; createdAfterSaleId.value = null; try { afterSaleSubmitting.value = true; const result = await createBuyerAfterSale({ orderId: detail.value.orderId, reason, evidenceImages }); afterSaleSuccessMessage.value = readAfterSaleSuccessMessage(result); createdAfterSaleId.value = result.afterSaleId; if (result.afterSaleId !== null) { disputeForm.afterSaleId = String(result.afterSaleId); clearDisputeMessages() } } catch (error: unknown) { afterSaleSuccessMessage.value = ''; createdAfterSaleId.value = null; afterSaleErrorMessage.value = readErrorMessage(error, '售后申请失败，请稍后重试。') } finally { afterSaleSubmitting.value = false } }
async function submitDisputeInitiate() { if (disputeSubmitting.value) return; const afterSaleId = readPositiveInt(disputeForm.afterSaleId); const content = disputeForm.content.trim(); if (afterSaleId === null) { disputeErrorMessage.value = '请输入有效的售后单号。'; return } if (content.length < 2 || content.length > 500) { disputeErrorMessage.value = '争议说明需为 2 至 500 个字。'; return } disputeErrorMessage.value = ''; disputeSuccessMessage.value = ''; try { disputeSubmitting.value = true; disputeSuccessMessage.value = await initiateBuyerAfterSaleDispute(afterSaleId, { content }) || '平台处理申请已提交。' } catch (error: unknown) { disputeSuccessMessage.value = ''; disputeErrorMessage.value = readErrorMessage(error, '平台处理申请失败，请稍后重试。') } finally { disputeSubmitting.value = false } }
async function loadDetail() { if (loading.value) return; if (!orderId.value) { errorMessage.value = '订单信息缺失，暂时无法加载详情。'; hasLoadedOnce.value = true; return } try { loading.value = true; errorMessage.value = ''; detail.value = await getBuyerOrderDetail(orderId.value) } catch (error: unknown) { errorMessage.value = readErrorMessage(error, '订单详情加载失败，请稍后重试。') } finally { loading.value = false; hasLoadedOnce.value = true } }
onMounted(() => { void loadDetail() })
</script>

<template>
  <div class="page-body"><section class="page-hero"><div class="page-hero-content"><div class="page-header-main"><p class="page-kicker">订单详情</p><h1 class="page-title">买家订单</h1><p class="page-desc">订单状态、商品快照和当前可执行操作都集中在这里。</p></div><div class="page-actions"><router-link class="btn-default" to="/orders/buyer"><ChevronLeft class="h-4 w-4" />返回订单列表</router-link></div></div></section>
    <section v-if="errorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span><div class="flex-1"><p class="font-semibold">订单详情加载失败</p><p class="mt-1 text-[12px] leading-5">{{ errorMessage }}</p><button class="btn-default mt-3" type="button" :disabled="loading" @click="loadDetail">重新加载</button></div></section>
    <section v-if="loading && !hasLoadedOnce" class="section-panel"><div class="empty-state min-h-[280px]"><Loader2 class="empty-state-icon animate-spin text-orange-600" /><p class="empty-state-title">正在加载订单详情</p></div></section>
    <template v-else><section class="section-panel"><div class="section-header"><div><div class="flex flex-wrap items-center gap-2"><h2 class="section-heading">{{ statusMeta.label }}</h2><span class="chip chip-accent">订单号：{{ detail.orderNo || '-' }}</span></div><p class="section-subtitle">下单时间：{{ detail.createTime || '-' }}</p></div></div><div class="section-body"><CommerceOrderStatusSteps :status="detail.status" :status-label="statusMeta.label" /></div></section>
      <section class="section-panel"><div class="section-header"><div><h2 class="section-heading">商品信息</h2><p class="section-subtitle">按本次交易快照展示商品和金额。</p></div></div><div class="section-body"><CommerceOrderProductSnapshot :product-id="detail.productId" :product-title="detail.productTitle" :product-thumbnail="primaryProductImage" :deal-price="detail.dealPrice" :quantity="detail.quantity" :total-amount="detail.totalAmount" counterpart-label="卖家" :counterpart-name="detail.sellerNickname" :create-time="detail.createTime" /></div></section>
      <section class="section-panel"><div class="section-header"><div><h2 class="section-heading">当前操作</h2><p class="section-subtitle">仅显示与当前订单状态匹配的操作。</p></div></div><div class="section-body space-y-4"><div v-if="actionErrorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span>{{ actionErrorMessage }}</div><div v-if="actionSuccessMessage" class="notice-banner notice-banner-success"><span class="notice-dot bg-emerald-500"></span>{{ actionSuccessMessage }}</div>
        <template v-if="detail.status === 'pending'"><div class="flex flex-wrap items-center gap-3"><router-link v-if="canEnterPaymentPage" class="btn-primary" :to="`/orders/buyer/${detail.orderId}/pay`">去支付</router-link><span v-else class="chip chip-neutral">当前暂不可支付</span></div><div class="max-w-xl"><label class="form-label" for="buyer-cancel-reason">取消原因（选填）</label><input id="buyer-cancel-reason" v-model="cancelReason" class="input-standard" maxlength="100" placeholder="不超过 100 字" :disabled="!canTriggerCancel" @input="clearActionMessages" /><button class="btn-default mt-3" type="button" :disabled="!canTriggerCancel" @click="submitCancelOrder"><Loader2 v-if="actionSubmitting" class="h-4 w-4 animate-spin" />取消订单</button></div></template>
        <p v-else-if="detail.status === 'paid'" class="text-[14px] text-stone-600">订单已支付，等待卖家发货。</p><template v-else-if="detail.status === 'shipped'"><p class="text-[14px] text-stone-600">订单已发货，请核对物流信息后确认收货。</p><button class="btn-primary" type="button" :disabled="!canTriggerConfirmReceipt" @click="submitConfirmReceipt"><Loader2 v-if="actionSubmitting" class="h-4 w-4 animate-spin" />确认收货</button></template>
        <template v-else-if="detail.status === 'completed'"><p class="text-[14px] text-stone-600">交易已完成。{{ afterSaleHint }}</p><div v-if="afterSaleErrorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span>{{ afterSaleErrorMessage }}</div><div v-if="afterSaleSuccessMessage" class="notice-banner notice-banner-success"><span class="notice-dot bg-emerald-500"></span>{{ afterSaleSuccessMessage }}</div><div class="grid gap-4 lg:grid-cols-2"><div><label class="form-label" for="buyer-after-sale-reason">售后原因</label><textarea id="buyer-after-sale-reason" v-model="afterSaleForm.reason" class="input-standard min-h-[112px]" maxlength="200" placeholder="请输入 2 至 200 个字" :disabled="afterSaleSubmitting" @input="clearAfterSaleMessages"></textarea></div><div><label class="form-label" for="buyer-after-sale-evidence-images">凭证图片链接（选填）</label><textarea id="buyer-after-sale-evidence-images" v-model="afterSaleForm.evidenceImageText" class="input-standard min-h-[112px]" placeholder="每行填写一个图片链接，最多 3 个" :disabled="afterSaleSubmitting" @input="clearAfterSaleMessages"></textarea></div></div><button class="btn-primary" type="button" :disabled="!canTriggerAfterSaleApply" @click="submitAfterSaleApply"><Loader2 v-if="afterSaleSubmitting" class="h-4 w-4 animate-spin" />提交售后申请</button><span v-if="createdAfterSaleId !== null" class="ml-3 chip chip-neutral">售后单号：{{ createdAfterSaleId }}</span></template>
        <p v-else-if="detail.status === 'cancelled'" class="text-[14px] text-stone-600">订单已取消，无需继续处理。</p><p v-else class="text-[14px] text-stone-600">当前状态暂无法识别，仅保留订单信息供查看。</p></div></section>
      <section v-if="detail.status === 'completed'" class="section-panel"><div class="section-header"><div><h2 class="section-heading">需要平台协助？</h2><p class="section-subtitle">仅已被卖家拒绝的售后申请可发起平台处理，最终结果以平台校验为准。</p></div></div><div class="section-body space-y-3"><div v-if="disputeErrorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span>{{ disputeErrorMessage }}</div><div v-if="disputeSuccessMessage" class="notice-banner notice-banner-success"><span class="notice-dot bg-emerald-500"></span>{{ disputeSuccessMessage }}</div><div class="grid gap-4 md:grid-cols-[14rem_minmax(0,1fr)]"><div><label class="form-label" for="buyer-dispute-after-sale-id">售后单号</label><input id="buyer-dispute-after-sale-id" v-model="disputeForm.afterSaleId" class="input-standard" inputmode="numeric" placeholder="例如 50001" :disabled="disputeSubmitting" @input="clearDisputeMessages" /></div><div><label class="form-label" for="buyer-dispute-content">争议说明</label><textarea id="buyer-dispute-content" v-model="disputeForm.content" class="input-standard min-h-[96px]" maxlength="500" placeholder="请输入 2 至 500 个字" :disabled="disputeSubmitting" @input="clearDisputeMessages"></textarea></div></div><button class="btn-default" type="button" :disabled="!canTriggerDisputeInitiate" @click="submitDisputeInitiate"><Loader2 v-if="disputeSubmitting" class="h-4 w-4 animate-spin" />提交平台处理</button></div></section>
      <section class="grid gap-6 lg:grid-cols-2"><section class="section-panel"><div class="section-header section-header-plain"><h2 class="section-heading">收货地址</h2></div><div class="section-body pt-0"><p class="break-words text-[13px] leading-6 text-stone-600">{{ detail.shippingAddress || '暂无地址快照' }}</p></div></section><section class="section-panel"><div class="section-header section-header-plain"><h2 class="section-heading">物流信息</h2></div><div class="section-body pt-0"><div class="detail-grid"><div class="detail-row"><span class="detail-label">物流公司</span><span class="detail-value">{{ detail.shippingCompany || '-' }}</span></div><div class="detail-row"><span class="detail-label">运单号</span><span class="detail-value break-all">{{ detail.trackingNo || '-' }}</span></div><div class="detail-row"><span class="detail-label">发货时间</span><span class="detail-value">{{ detail.shipTime || '-' }}</span></div><div class="detail-row"><span class="detail-label">完成时间</span><span class="detail-value">{{ detail.completeTime || '-' }}</span></div></div></div></section></section>
      <OrderMessagePanel :order-id="detail.orderId" :current-user-id="detail.buyerId" :counterpart-user-id="detail.sellerId" :counterpart-label="detail.sellerNickname || '卖家'" />
    </template>
  </div>
</template>
