<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { Loader2, PackageSearch, RefreshCw, Truck } from 'lucide-vue-next'
import { createEmptySellerOrderDetail, createEmptySellerOrderLogistics, getSellerOrderDetail, getSellerOrderLogistics, getSellerOrderStatusMeta, readShipSellerOrderValidationError, shipSellerOrder, type SellerOrderDetail, type SellerOrderLogistics } from '@/api/orders'
import OrderMessagePanel from '@/pages/orders/components/OrderMessagePanel.vue'
import CommerceOrderProductSnapshot from '@/components/commerce/CommerceOrderProductSnapshot.vue'
import CommerceOrderStatusSteps from '@/components/commerce/CommerceOrderStatusSteps.vue'
import { isSellerUser, readCurrentUser } from '@/utils/request'

const route = useRoute(); const sellerEnabled = computed(() => isSellerUser(readCurrentUser())); const loading = ref(false); const hasLoadedOnce = ref(false); const errorMessage = ref(''); const detail = ref<SellerOrderDetail>(createEmptySellerOrderDetail())
const logisticsLoading = ref(false); const logisticsErrorMessage = ref(''); const logistics = ref<SellerOrderLogistics>(createEmptySellerOrderLogistics()); const shipSubmitting = ref(false); const shipErrorMessage = ref(''); const shipSuccessMessage = ref(''); const shipForm = reactive({ shippingCompany: '', trackingNo: '', remark: '' })
const orderId = computed(() => { const raw = route.params.orderId; return Array.isArray(raw) ? raw[0] || '' : typeof raw === 'string' ? raw : '' }); const statusMeta = computed(() => getSellerOrderStatusMeta(detail.value.status)); const primaryProductImage = computed(() => detail.value.productImages[0] || detail.value.productThumbnail)
const shipValidationError = computed(() => readShipSellerOrderValidationError(shipForm)); const canEditShipFields = computed(() => sellerEnabled.value && detail.value.orderId !== null && detail.value.status === 'paid' && !loading.value && !shipSubmitting.value); const canSubmitShip = computed(() => canEditShipFields.value && !shipValidationError.value)
const logisticsEmptyText = computed(() => detail.value.status === 'pending' ? '买家尚未支付，物流轨迹尚未开始。' : detail.value.status === 'paid' ? '订单待发货，当前暂无物流轨迹。' : detail.value.status === 'cancelled' ? '订单已取消，物流轨迹不再更新。' : '当前暂无物流轨迹，可稍后刷新再看。')
function readErrorMessage(error: unknown, fallback: string) { return error instanceof Error && error.message.trim() ? error.message : fallback }
function syncShipFormFromDetail() { shipForm.shippingCompany = detail.value.shippingCompany; shipForm.trackingNo = detail.value.trackingNo; shipForm.remark = detail.value.shippingRemark }
function clearShipMessages() { if (!shipSubmitting.value) { shipErrorMessage.value = ''; shipSuccessMessage.value = '' } }
async function loadLogistics(targetOrderId: number | string) { try { logisticsLoading.value = true; logisticsErrorMessage.value = ''; logistics.value = await getSellerOrderLogistics(targetOrderId) } catch (error: unknown) { logisticsErrorMessage.value = readErrorMessage(error, '物流信息加载失败，请稍后重试。'); logistics.value = createEmptySellerOrderLogistics() } finally { logisticsLoading.value = false } }
async function loadPage() { if (loading.value || !sellerEnabled.value) return; try { loading.value = true; errorMessage.value = ''; detail.value = await getSellerOrderDetail(orderId.value); syncShipFormFromDetail(); if (detail.value.orderId !== null) await loadLogistics(detail.value.orderId) } catch (error: unknown) { errorMessage.value = readErrorMessage(error, '卖家订单详情加载失败，请稍后重试。'); detail.value = createEmptySellerOrderDetail(); logistics.value = createEmptySellerOrderLogistics() } finally { loading.value = false; hasLoadedOnce.value = true } }
async function refreshLogistics() { if (detail.value.orderId !== null && !logisticsLoading.value) await loadLogistics(detail.value.orderId) }
async function submitShip() { if (shipSubmitting.value || detail.value.orderId === null) return; const validationError = readShipSellerOrderValidationError(shipForm); if (validationError) { shipErrorMessage.value = validationError; shipSuccessMessage.value = ''; return } try { shipSubmitting.value = true; shipErrorMessage.value = ''; shipSuccessMessage.value = ''; shipSuccessMessage.value = await shipSellerOrder(detail.value.orderId, shipForm); await loadPage() } catch (error: unknown) { shipErrorMessage.value = readErrorMessage(error, '发货失败，请稍后重试。'); shipSuccessMessage.value = '' } finally { shipSubmitting.value = false } }
function fulfillmentText() { if (detail.value.status === 'pending') return '等待买家支付后再发货。'; if (detail.value.status === 'shipped') return '订单已发货，无需重复提交。'; if (detail.value.status === 'completed') return '交易已完成。'; if (detail.value.status === 'cancelled') return '订单已取消，不能发货。'; return '当前状态暂无法识别。' }
onMounted(() => { if (sellerEnabled.value) void loadPage(); else hasLoadedOnce.value = true })
</script>

<template>
  <div class="page-body"><section class="page-hero"><div class="page-hero-content"><div class="page-header-main"><p class="page-kicker">卖家履约</p><h1 class="page-title">订单详情</h1><p class="page-desc">核对交易信息、完成发货并查看物流进度。</p></div><div class="page-actions"><router-link class="btn-default" to="/orders/seller">返回卖家订单</router-link><button class="btn-default" type="button" :disabled="loading || !sellerEnabled" @click="loadPage"><Loader2 v-if="loading" class="h-4 w-4 animate-spin" /><RefreshCw v-else class="h-4 w-4" />刷新</button></div></div></section>
    <section v-if="!sellerEnabled" class="notice-banner notice-banner-warning"><span class="notice-dot bg-orange-500"></span><span>当前账号暂未启用卖家功能，无法查看或处理卖家订单。</span></section><section v-else-if="errorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span><div class="flex-1"><p class="font-semibold">订单详情加载失败</p><p class="mt-1 text-[12px] leading-5">{{ errorMessage }}</p><button class="btn-default mt-3" type="button" @click="loadPage">重新加载</button></div></section><section v-if="loading && !hasLoadedOnce && sellerEnabled" class="section-panel"><div class="empty-state min-h-[300px]"><Loader2 class="empty-state-icon animate-spin text-orange-600" /><p class="empty-state-title">正在加载订单详情</p></div></section>
    <template v-else-if="sellerEnabled && detail.orderId !== null"><section class="section-panel"><div class="section-header"><div><div class="flex flex-wrap items-center gap-2"><h2 class="section-heading">{{ statusMeta.label }}</h2><span class="chip chip-accent">订单号：{{ detail.orderNo || '-' }}</span></div><p class="section-subtitle">买家：{{ detail.buyerNickname || '-' }} · 下单时间：{{ detail.createTime || '-' }}</p></div></div><div class="section-body"><CommerceOrderStatusSteps :status="detail.status" :status-label="statusMeta.label" /></div></section>
      <section class="section-panel"><div class="section-header"><div><h2 class="section-heading">商品信息</h2><p class="section-subtitle">请以订单快照为准完成履约。</p></div></div><div class="section-body"><CommerceOrderProductSnapshot :product-id="detail.productId" :product-title="detail.productTitle" :product-thumbnail="primaryProductImage" :deal-price="detail.dealPrice" :quantity="detail.quantity" :total-amount="detail.totalAmount" counterpart-label="买家" :counterpart-name="detail.buyerNickname" :create-time="detail.createTime" /></div></section>
      <section class="section-panel"><div class="section-header"><div><h2 class="section-heading">发货</h2><p class="section-subtitle">{{ detail.status === 'paid' ? '填写真实物流信息后提交发货。' : fulfillmentText() }}</p></div></div><div class="section-body space-y-4"><div v-if="shipErrorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span>{{ shipErrorMessage }}</div><div v-if="shipSuccessMessage" class="notice-banner notice-banner-success"><span class="notice-dot bg-emerald-500"></span>{{ shipSuccessMessage }}</div><template v-if="detail.status === 'paid'"><div class="grid gap-4 lg:grid-cols-3"><div><label class="form-label" for="seller-ship-company">物流公司</label><input id="seller-ship-company" v-model="shipForm.shippingCompany" class="input-standard" maxlength="50" placeholder="例如：顺丰速运" :disabled="!canEditShipFields" @input="clearShipMessages" /></div><div><label class="form-label" for="seller-ship-tracking-no">运单号</label><input id="seller-ship-tracking-no" v-model="shipForm.trackingNo" class="input-standard" maxlength="50" placeholder="6 至 50 位字母、数字或中划线" :disabled="!canEditShipFields" @input="clearShipMessages" /></div><div><label class="form-label" for="seller-ship-remark">发货备注（选填）</label><input id="seller-ship-remark" v-model="shipForm.remark" class="input-standard" maxlength="200" placeholder="不超过 200 个字" :disabled="!canEditShipFields" @input="clearShipMessages" /></div></div><button class="btn-primary" type="button" :disabled="!canSubmitShip" @click="submitShip"><Loader2 v-if="shipSubmitting" class="h-4 w-4 animate-spin" /><Truck v-else class="h-4 w-4" />提交发货</button><p v-if="shipValidationError" class="form-helper">{{ shipValidationError }}</p></template><p v-else class="text-[14px] text-stone-600">{{ fulfillmentText() }}</p></div></section>
      <section class="grid gap-6 lg:grid-cols-2"><section class="section-panel"><div class="section-header"><div><h2 class="section-heading">物流信息</h2><p class="section-subtitle">物流信息以最新查询结果为准。</p></div><button class="btn-default !h-9 px-3" type="button" :disabled="logisticsLoading" @click="refreshLogistics"><Loader2 v-if="logisticsLoading" class="h-4 w-4 animate-spin" /><RefreshCw v-else class="h-4 w-4" />刷新物流</button></div><div class="section-body space-y-4"><div v-if="logisticsErrorMessage" class="notice-banner notice-banner-warning"><span class="notice-dot bg-orange-500"></span>{{ logisticsErrorMessage }}</div><div class="detail-grid"><div class="detail-row"><span class="detail-label">物流公司</span><span class="detail-value">{{ logistics.shippingCompany || detail.shippingCompany || '-' }}</span></div><div class="detail-row"><span class="detail-label">运单号</span><span class="detail-value break-all">{{ logistics.trackingNo || detail.trackingNo || '-' }}</span></div><div class="detail-row"><span class="detail-label">物流数据来源</span><span class="detail-value">{{ logistics.provider || '-' }}</span></div><div class="detail-row"><span class="detail-label">最近同步</span><span class="detail-value">{{ logistics.lastSyncTime || '-' }}</span></div></div><ol v-if="logistics.trace.length" class="logistics-timeline"><li v-for="item in logistics.trace" :key="`${item.time}-${item.location}-${item.status}`"><p class="font-numeric text-[12px] text-stone-500">{{ item.time || '-' }}</p><p class="mt-1 text-[13px] font-medium text-stone-800">{{ item.status || '-' }}</p><p class="mt-1 break-words text-[12px] text-stone-500">{{ item.location || '-' }}</p></li></ol><div v-else class="empty-state min-h-[190px]"><PackageSearch class="empty-state-icon" /><p class="empty-state-title">暂无物流轨迹</p><p class="empty-state-text">{{ logisticsEmptyText }}</p></div></div></section><section class="section-panel"><div class="section-header section-header-plain"><h2 class="section-heading">收货地址</h2></div><div class="section-body pt-0"><p class="break-words text-[13px] leading-6 text-stone-600">{{ detail.shippingAddress || '暂无地址快照' }}</p><div class="mt-5 detail-grid"><div class="detail-row"><span class="detail-label">支付时间</span><span class="detail-value">{{ detail.payTime || '-' }}</span></div><div class="detail-row"><span class="detail-label">发货时间</span><span class="detail-value">{{ detail.shipTime || '-' }}</span></div><div class="detail-row"><span class="detail-label">完成时间</span><span class="detail-value">{{ detail.completeTime || '-' }}</span></div></div></div></section></section>
      <OrderMessagePanel :order-id="detail.orderId" :current-user-id="detail.sellerId" :counterpart-user-id="detail.buyerId" :counterpart-label="detail.buyerNickname || '买家'" />
    </template>
  </div>
</template>

<style scoped>
.logistics-timeline { margin-left: 0.4rem; border-left: 2px solid #fed7aa; padding-left: 1rem; }.logistics-timeline li { position: relative; padding: 0 0 1.25rem; }.logistics-timeline li::before { position: absolute; top: 0.25rem; left: -1.375rem; width: 0.625rem; height: 0.625rem; border: 2px solid #ea580c; border-radius: 999px; background: #fff; content: ''; }
</style>
