<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { CheckCircle2, Loader2, XCircle } from 'lucide-vue-next'
import { submitSellerAfterSaleDecision } from '@/api/afterSales'
import { isSellerUser, readCurrentUser } from '@/utils/request'

const route = useRoute(); const sellerEnabled = computed(() => isSellerUser(readCurrentUser())); const submitting = ref(false); const errorMessage = ref(''); const successMessage = ref(''); const form = reactive({ afterSaleId: '', decision: '', remark: '' })
function readPositiveInt(value: unknown) { if (typeof value === 'number' && Number.isInteger(value) && value > 0) return value; if (typeof value === 'string' && /^\d+$/.test(value.trim())) { const parsed = Number(value.trim()); return parsed > 0 ? parsed : null } return null }
function readQueryAfterSaleId(value: unknown) { if (Array.isArray(value)) return readQueryAfterSaleId(value[0]); if (typeof value === 'number' && Number.isFinite(value)) return String(Math.trunc(value)); return typeof value === 'string' ? value.trim() : '' }
const normalizedAfterSaleId = computed(() => readPositiveInt(form.afterSaleId)); const approvedValue = computed<boolean | null>(() => form.decision === 'approve' ? true : form.decision === 'reject' ? false : null); const trimmedRemark = computed(() => form.remark.trim()); const queryAfterSaleId = computed(() => readQueryAfterSaleId(route.query.afterSaleId))
const validationError = computed(() => { if (!sellerEnabled.value) return '当前账号暂未启用卖家功能，无法提交售后处理。'; if (normalizedAfterSaleId.value === null) return '请输入有效的售后单号。'; if (approvedValue.value === null) return '请选择处理结果。'; if (trimmedRemark.value.length > 200) return '处理备注不能超过 200 个字。'; return '' })
const canSubmit = computed(() => !submitting.value && !validationError.value)
function syncAfterSaleIdFromQuery(value: unknown) { const id = readQueryAfterSaleId(value); if (id) form.afterSaleId = id }
function clearMessages() { if (!submitting.value) { errorMessage.value = ''; successMessage.value = '' } }
async function submitDecision() { if (submitting.value) return; if (validationError.value || normalizedAfterSaleId.value === null || approvedValue.value === null) { errorMessage.value = validationError.value || '售后处理信息不完整，请检查后重试。'; successMessage.value = ''; return } errorMessage.value = ''; successMessage.value = ''; try { submitting.value = true; successMessage.value = await submitSellerAfterSaleDecision(normalizedAfterSaleId.value, { approved: approvedValue.value, remark: trimmedRemark.value }); errorMessage.value = '' } catch (error: unknown) { successMessage.value = ''; errorMessage.value = error instanceof Error && error.message.trim() ? error.message : '售后处理失败，请稍后重试。' } finally { submitting.value = false } }
watch(() => route.query.afterSaleId, (value) => { syncAfterSaleIdFromQuery(value) }, { immediate: true })
</script>

<template>
  <div class="page-body"><section class="page-hero"><div class="page-hero-content"><div class="page-header-main"><p class="page-kicker">卖家售后</p><h1 class="page-title">按售后单号处理</h1><p class="page-desc">输入售后单号，选择处理结果并提交。本页不展示无法查询到的售后详情。</p></div><div class="page-actions"><router-link class="btn-default" to="/orders/seller">查看卖家订单</router-link></div></div></section>
    <section v-if="!sellerEnabled" class="notice-banner notice-banner-warning"><span class="notice-dot bg-orange-500"></span><span>当前账号暂未启用卖家功能，无法提交售后处理。</span></section>
    <section class="section-panel"><div class="section-header"><div><h2 class="section-heading">处理售后申请</h2><p class="section-subtitle">提交后将按所选结果处理该售后申请，请核对售后单号和处理结果。</p></div></div><div class="section-body space-y-5"><ol class="after-sale-steps"><li>输入售后单号</li><li>选择同意或拒绝</li><li>确认提交处理结果</li></ol><p v-if="queryAfterSaleId" class="chip chip-neutral">已从链接带入售后单号</p><div v-if="errorMessage" class="notice-banner notice-banner-danger"><span class="notice-dot bg-red-500"></span>{{ errorMessage }}</div><div v-if="successMessage" class="notice-banner notice-banner-success"><span class="notice-dot bg-emerald-500"></span>{{ successMessage }}</div><div class="grid gap-4 lg:grid-cols-[15rem_minmax(0,1fr)]"><div><label class="form-label" for="seller-decision-after-sale-id">售后单号</label><input id="seller-decision-after-sale-id" v-model="form.afterSaleId" class="input-standard" inputmode="numeric" maxlength="20" placeholder="请输入售后单号" :disabled="submitting" @input="clearMessages" /></div><div><label class="form-label" for="seller-decision-remark">处理备注（选填）</label><textarea id="seller-decision-remark" v-model="form.remark" class="input-standard min-h-[96px]" maxlength="200" placeholder="不超过 200 个字" :disabled="submitting" @input="clearMessages"></textarea></div></div><fieldset :disabled="submitting"><legend class="form-label">处理结果</legend><div class="grid gap-3 sm:grid-cols-2"><label class="after-sale-choice" :class="{ 'after-sale-choice-approved': form.decision === 'approve' }"><input v-model="form.decision" type="radio" value="approve" class="sr-only" @change="clearMessages" /><CheckCircle2 class="h-5 w-5" aria-hidden="true" /><span><strong>同意退货退款</strong><small>确认同意本次售后处理。</small></span></label><label class="after-sale-choice" :class="{ 'after-sale-choice-rejected': form.decision === 'reject' }"><input v-model="form.decision" type="radio" value="reject" class="sr-only" @change="clearMessages" /><XCircle class="h-5 w-5" aria-hidden="true" /><span><strong>拒绝退货退款</strong><small>请在备注中说明处理原因。</small></span></label></div></fieldset><div class="flex flex-wrap items-center gap-3"><button class="btn-primary" type="button" :disabled="!canSubmit" @click="submitDecision"><Loader2 v-if="submitting" class="h-4 w-4 animate-spin" />提交处理结果</button><span v-if="validationError && sellerEnabled" class="text-[12px] text-stone-500">{{ validationError }}</span></div></div></section>
  </div>
</template>

<style scoped>
.after-sale-steps { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0.75rem; color: #57534e; font-size: 0.8125rem; }.after-sale-steps li { padding: 0.625rem 0.75rem; border-radius: 0.5rem; background: #fff7ed; }.after-sale-choice { display: flex; gap: 0.75rem; min-height: 5rem; padding: 1rem; border: 1px solid #e7e5e4; border-radius: 0.5rem; color: #78716c; cursor: pointer; }.after-sale-choice strong, .after-sale-choice small { display: block; }.after-sale-choice strong { color: #292524; font-size: 0.875rem; }.after-sale-choice small { margin-top: 0.25rem; font-size: 0.75rem; line-height: 1.25rem; }.after-sale-choice-approved { border-color: #34d399; color: #059669; background: #ecfdf5; }.after-sale-choice-rejected { border-color: #fb923c; color: #c2410c; background: #fff7ed; } @media (max-width: 520px) { .after-sale-steps { grid-template-columns: 1fr; } }
</style>
